export const USER_PENDING = "USER_PENDING";
export const USER_FULFILLED = "USER_FULFILLED";
export const USER_REJECTED = "USER_REJECTED";
export const USER_EDIT_PENDING = "USER_EDIT_PENDING";
export const USER_EDIT_FULFILLED = "USER_EDIT_FULFILLED";
export const USER_EDIT_REJECTED = "USER_EDIT_REJECTED";

export const VACATIONS_PENDING = "VACATIONS_PENDING";
export const VACATIONS_FULFILLED = "VACATIONS_FULFILLED";
export const VACATIONS_REJECTED = "VACATIONS_REJECTED";