export const USER_PENDING = "USER_PENDING";
export const USER_FULFILLED = "USER_FULFILLED";
export const USER_REJECTED = "USER_REJECTED";
export const USER_EDIT_PENDING = "USER_EDIT_PENDING";
export const USER_EDIT_FULFILLED = "USER_EDIT_FULFILLED";
export const USER_EDIT_REJECTED = "USER_EDIT_REJECTED";

export const VACATIONS_PENDING = "VACATIONS_PENDING";
export const VACATIONS_FULFILLED = "VACATIONS_FULFILLED";
export const VACATIONS_REJECTED = "VACATIONS_REJECTED";

export const VACATION_SHOW_PENDING = "VACATION_SHOW_PENDING";
export const VACATION_SHOW_FULFILLED = "VACATION_SHOW_FULFILLED";
export const VACATION_SHOW_REJECTED = "VACATION_SHOW_REJECTED";

export const VACATION_CREATE_PENDING = "VACATION_CREATE_PENDING";
export const VACATION_CREATE_FULFILLED = "VACATION_CREATE_FULFILLED";
export const VACATION_CREATE_REJECTED = "VACATION_CREATE_REJECTED";

export const VACATION_UPDATE_PENDING = "VACATION_UPDATE_PENDING";
export const VACATION_UPDATE_FULFILLED = "VACATION_UPDATE_FULFILLED";
export const VACATION_UPDATE_REJECTED = "VACATION_UPDATE_REJECTED";

export const VACATION_DELETE_PENDING = "VACATION_DELETE_PENDING";
export const VACATION_DELETE_FULFILLED = "VACATION_DELETE_FULFILLED";
export const VACATION_DELETE_REJECTED = "VACATION_DELETE_REJECTED";
